### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by georgkrause** [derricw/siggo#41]
I updated signal-cli to 0.8.0 and siggo to 0.9.0 and have constant crashes:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7ed634]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc0001ea1c0)
	/home/georg/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200329194346-7cc182c5846e/application.go:244 +0x87
panic(0x8557a0, 0xcae5c0)
	/usr/lib/go/src/runtime/panic.go:969 +0x1b9
github.com/derricw/siggo/widgets.(*ContactListPanel).Render(0xc000251280)
	/home/georg/workspace/siggo/widgets/contactlist.go:73 +0x494
github.com/derricw/siggo/widgets.(*ChatWindow).update(0xc0002f6870)
	/home/georg/workspace/siggo/widgets/chatwindow.go:432 +0x68
github.com/derricw/siggo/widgets.NewChatWindow.func3.1()
	/home/georg/workspace/siggo/widgets/chatwindow.go:601 +0x2a
github.com/rivo/tview.(*Application).QueueUpdateDraw.func1()
	/home/georg/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200329194346-7cc182c5846e/application.go:716 +0x2f
github.com/rivo/tview.(*Application).Run(0xc0001ea1c0, 0x0, 0x0)
	/home/georg/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200329194346-7cc182c5846e/application.go:371 +0x9a7
github.com/derricw/siggo/cmd.glob..func10(0xcb6b40, 0xced1b0, 0x0, 0x0)
	/home/georg/workspace/siggo/cmd/root.go:121 +0x45a
github.com/spf13/cobra.(*Command).execute(0xcb6b40, 0xc0001101b0, 0x0, 0x0, 0xcb6b40, 0xc0001101b0)
	/home/georg/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xcb6b40, 0x408025, 0xc000100058, 0x0)
	/home/georg/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	/home/georg/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/derricw/siggo/cmd.Execute()
	/home/georg/workspace/siggo/cmd/root.go:131 +0x31
main.main()
	/home/georg/workspace/siggo/main.go:8 +0x25
```

I suppose this is related to group messages, but I can't say this for sure. I can provide more debug information if needed.

**Comment by georgkrause** [comment]
I try to run the latest master to verify if it might be solved already

**Comment by derricw** [comment]
Hey! Thanks for the report. I have not tested siggo with signal-cli 0.8.0 yet. I'll take a look at this as soon as I can.

**Comment by oto-ledger** [comment]
I've got the exact same issue, with signal-cli 0.8.1 and release 0.9 of siggo

`
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7e6bd9]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc0002d41c0)
        /Users/wilzder/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200329194346-7cc182c5846e/application.go:244 +0x87
panic(0x84dd20, 0xca12b0)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/derricw/siggo/model.(*Conversation).HasStagedMessage(...)
        /Users/wilzder/code/github/siggo/model/model.go:337
github.com/derricw/siggo/model.(*Conversation).HasStagedData(...)
        /Users/wilzder/code/github/siggo/model/model.go:342
github.com/derricw/siggo/widgets.(*ContactListPanel).Render(0xc0001cb140)
        /Users/wilzder/code/github/siggo/widgets/contactlist.go:78 +0x3f9
github.com/derricw/siggo/widgets.(*ChatWindow).update(0xc0002b66c0)
        /Users/wilzder/code/github/siggo/widgets/chatwindow.go:432 +0x68
github.com/derricw/siggo/widgets.NewChatWindow.func3.1()
        /Users/wilzder/code/github/siggo/widgets/chatwindow.go:601 +0x2a
github.com/rivo/tview.(*Application).QueueUpdateDraw.func1()
        /Users/wilzder/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200329194346-7cc182c5846e/application.go:716 +0x2f
github.com/rivo/tview.(*Application).Run(0xc0002d41c0, 0x0, 0x0)
        /Users/wilzder/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200329194346-7cc182c5846e/application.go:371 +0x9a7
github.com/derricw/siggo/cmd.glob..func10(0xca9840, 0xcdff10, 0x0, 0x0)
        /Users/wilzder/code/github/siggo/cmd/root.go:121 +0x45a
github.com/spf13/cobra.(*Command).execute(0xca9840, 0xc0000101d0, 0x0, 0x0, 0xca9840, 0xc0000101d0)
        /Users/wilzder/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xca9840, 0x406225, 0xc000066058, 0x0)
        /Users/wilzder/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/wilzder/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/derricw/siggo/cmd.Execute()
        /Users/wilzder/code/github/siggo/cmd/root.go:131 +0x31
main.main()
        /Users/wilzder/code/github/siggo/main.go:8 +0x25
`
